### PR TITLE
Added VBN unpack support.

### PR DESCRIPTION
**Pull request by ronbarrey**
Added .txt extension to eml.py as possible .eml file.
Please let me know if I need to make any changes or if you have any questions.

### CODE REVIEW

**Comment by wroersma** [comment]
Can we get a bump on this going in? Is there anything that needs to be changed that would speed this up?

**Comment by jbremer** [comment]
Sorry for my late reply, @wroersma @ronbarrey. Yes, adding one or two unit tests or at least sharing some `.vbn` files would certainly speed this up. Thanks in advance.

**Comment by wroersma** [comment]
Ok we will go ahead and add that in thanks for letting us know!

**Comment by jbremer** [comment]
@wroersma @ronbarrey does either of you have the `.vbn` sample file? Thanks.

**Comment by wroersma** [comment]
That's actually my biggest hold up right now! We have no sample's we can share publicly as the test code is not hard to write at all. If you happen to know anyone or have samples that would be amazing!

**Comment by ronbarrey** [comment]
Removed conflicts

**Pull request closed without merging**
